### ISSUE TITLE
Only supported for even number of covariate factors?

### ISSUE THREAD

**Issue by nainai123** [cran/Minirand#1]
Dear developer,

I am using this great package to do minimization randomizaiton. The algorithm worked perfectly with the example provided in help document. However, I encountered an error using my own dummy dataset (It looked like this function only works for even # of covariate factors?). For your reference, I've attached my codes below:

nsample <- 16
trtseq <- c(1, 2, 3)
ratio <- c(1, 1, 1)
install.packages('jsonlite')
library(jsonlite)

covmat_tmp = '{"var1": ["10", "1", "1", "1", "1", "1", "1", "1","10", "1", "1", "1", "1", "1", "1", "1"],"var2": ["2", "2", "2", "2", "2", "2", "1", "2","2", "2", "2", "2", "2", "2", "1", "2"],
  "var3": ["2", "1", "1", "1", "1", "1", "1", "1","2", "1", "1", "1", "1", "1", "1", "1"],"var4": ["2", "1", "1", "1", "1", "1", "1", "1","2", "1", "1", "1", "1", "1", "1", "1"],
"var5": ["2", "1", "1", "1", "1", "1", "1", "1","2", "1", "1", "1", "1", "1", "1", "1"]}'

#(**5** covariate factors in total)

covmat = jsonlite::fromJSON(covmat_tmp) %>% data.frame()

covwt <- c(1/3 ,1/3, 1/3)

res <- rep(100, nsample)
  res[1] = sample(trtseq, 1, replace = TRUE, prob = ratio/sum(ratio)) 
  for (j in 2:nsample)
  {
    res[j] <- Minirand(covmat=covmat, j, covwt=covwt, ratio=ratio, 
                       ntrt=ntrt, trtseq=trtseq, method="Range", result=res, p = 0.9)
  }

Thank you for your help, I am looking forward to hearing from you!

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!

**Comment by nainai123** [comment]
> Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!

Thank you for your prompt response. I have already figured it out. It looked like this function only accept the covmat as a numeric dataframe.
